### ISSUE TITLE
discrepancy between gpx::read and GPX schema documentation

### ISSUE THREAD

**Issue by felgru** [georust/gpx#21]
In [src/parser/waypoint.rs](https://github.com/georust/gpx/blob/eee4066eb4ebf920ed19b17c23128955805a7f94/src/parser/waypoint.rs#L125) the element "ageofgpsdata" gets parsed into the `age` filed of the `Waypoint` object. Comparing that with the [GPX 1.1 shema](http://www.topografix.com/GPX/1/1/#type_wptType), there is no "ageofgpsdata" in a waypoint element. Instead there exists an "ageof**d**gpsdata" element. That would also be somewhat consistent with the [documentation of the `age` attribute](https://github.com/georust/gpx/blob/master/src/types.rs#L254) of the `Waypoint` class, which speaks of seconds since the last **D**GPS update.

The `Waypoint` parser should probably be changed to be able to parse "ageof**d**gpsdata" elements into the `age` attribute.

I’m not sure what to do about "ageofgpsdata" elements (without d). Those are actually used in the example file [tests/fixtures/with_accuracy.gpx](https://github.com/georust/gpx/blob/master/tests/fixtures/with_accuracy.gpx). If there are non-conforming gpx files in the wild that have waypoints with an "ageofgpsdata" element, we should probably be able to read them.

**Comment by oherrala** [comment]
Both GPX specifications 1.0 and 1.1 have "age of DGPS data" field, but no "age of GPS data" field.

Since "age of GPS" is unknown field in the specifications, there's no way we could understand what to do with that data. However, "age of DGPS" has specified usage.

Unfortunately there seem to be plenty of code with similar mistake: https://github.com/search?q=ageofgpsdata&type=Code

I expect this just to be unfortunate misspelling. Changing the field name is backwards incompatible change, but doing it will fix this crate to conform to specification.

**Comment by oherrala** [comment]
I opened PR #35 to fix the field naming.

**Comment by urschrei** [comment]
Since this is a breaking change it might be better to add the new, correctly-named field, use it for all operations, and add a deprecation notice to the existing field instead, in order to give crate users a chance to migrate.

**Comment by oherrala** [comment]
@urschrei How do you like what's currently in #35?

**Comment by urschrei** [comment]
@oherrala Looks good to me!
