### ISSUE TITLE
How to access the time of a waypoint?

### ISSUE THREAD

**Issue by gerritsangel** [georust/gpx#79]
Hello,

Thanks a lot for the crate! This makes handling of gpx files really easy.

I have one question though: How can I, as a consumer, properly work with the time of a waypoint? Maybe I'm missing it, but although with the newest commit, the Time struct is exported, I can only format it directly to a string. I would like to have it as a chrono `DateTime` to further do some calculations on it.

Currently it seems that I have to format it as a String (involving an allocation), just to have it again parsed again by chrono.

What about a chrono feature of the crate, which could transform the Time as a chrono DateTime?

**Comment by major-seven** [comment]
I just wanted to come here and ask exactly the same thing. :)
I think a quick workaround would be to just use OffsetDateTime::parse(time_string) since it seems to be only possible to extract the time as a string. However it would be more efficient to directly use the already existing OffsetDateTime. Is there a reason that the OffsetDateTime field in the gps Time struct is private and not public?

**Comment by michaelkirk** [comment]
So it looks like the feature has been added and at this point we're just waiting on a release, is that right?

@lnicola - would you be interested in becoming a publisher for this crate?

**Comment by michaelkirk** [comment]
> would you be interested in becoming a publisher for this crate?

Added - publish at will!

**Comment by lnicola** [comment]
I'll try to do this tomorrow.. where did the last 10 days go? :cry:

**Comment by jscatena88** [comment]
Looks like this still hasn't been published. Any chance to make it happen?

**Comment by lnicola** [comment]
Looking into it now, sorry. First part is https://github.com/georust/gpx/pull/86.

**Comment by lnicola** [comment]
`gpx` 0.9.0 is up on crates.io, I hope I didn't mess something up.
